### ISSUE TITLE
KAS ECC ephemeralUnified VAL errors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#389]
The ephemeralUnified VAL test requires the IUT to generate the hash of the shared secret and compare it to the value delivered by the ACVP server.

I see very interesting failures: For some of my responses, the ACVP server reports that my answer is not correct. The interesting thing is that this applies only to test results where my IUT's shared secret matches the one delivered by the ACVP server. Yet the ACVP server thinks that my shared secret should be different.

If it would be the other way round (the ACVP server expects a passing verdict but my IUT reports a failure), I would consider that my IUT is broken. But since my IUT generates exactly the shared secret values delivered by the ACVP (which is highly unlikely unless the values are correct), I would think that the ACVP ser
ver may have an issue.

Please see vsID 4389, tcIDs 21, 22, 50, 67 as examples.

**Comment by celic** [comment]
I'll do some investigating and see if I can figure out what's going on.

**Comment by celic** [comment]
I'm not as familiar with the KAS test going on here, but the server (as reported in the validation.json) says that these tests are expected to result in `"result": "fail"` instead of the `"result": "pass"` that is provided by your IUT.

**Comment by celic** [comment]
Just because the values can be used to lead to the same value at the end doesn't mean that the process is correct (and would lead to a "pass" verdict). The IUT must check the starting values to ensure that they are valid. Does the IUT check the validity of the domain parameters prior to computing the shared secret?

**Comment by celic** [comment]
As an aside, I've logged it in our internal system to include the 'failure reason' in the validation.json file to provide more useful information to the IUT than just "expected failure". This will make KAS similar to other algorithms such as SigVer (for any signature algorithm) where the reason is provided if the IUT doesn't get it right.

**Comment by smuellerDD** [comment]
We are talking about ECC here. So there are no domain parameters. Maybe you can check whether the point is on the curve. Are you saying that the point is not on the curve that the ACVP server relays?

Note, when calculating the same value as provided by the ACVP server, the ECDH mathematical operation for the shared secret generation works as it would on the ACVP server. Thus, the only reason that can or should lead to an (expected) failure is when the public key x/y affine coordinates are not on the curve (and thus should simply reject the key instead of proceeding with the shared secret operation).

**Comment by smuellerDD** [comment]
Just to be clear: we are talking about OpenSSL 1.1.0 as the IUT -- when looking at the code that sets the affine coordinates to the internal representation via the function EC_KEY_set_public_key_affine_coordinates, I see that there are checks implemented that verify that the coordinates are proper.

**Comment by celic** [comment]
I've confirmed where the issue is and am working on a solution. Thank you for the help in debugging this.

**Comment by celic** [comment]
Does this issue occur on just ECC ephemeralUnified? or do you notice the issue on other schemes (ECC or otherwise)?

**Comment by smuellerDD** [comment]
Yes, staticUnified, onePassDh: see 5315 for example.

I have not tested others.

**Comment by smuellerDD** [comment]
Note, it also happens on FFC, too.

**Comment by hbooth** [comment]
Fix has been deployed.

**Comment by smuellerDD** [comment]
KAS-ECC: confirmed working

KAS-FFC: still not working (vsID 7133)

**Comment by smuellerDD** [comment]
Correction: KAS-ECC is not working (vsID 7106) -- I was erroneously looking at the CDH-component testing initially.

**Comment by celic** [comment]
Ok. It should be noted that this is a different problem on a different scheme of KAS. The original problem was fixed as shown by the vsId posted. I will open a new issue with the relevant information to help keep the topics separate.

**Comment by smuellerDD** [comment]
can we close that issue then?
