### ISSUE TITLE
AES-XPN test vector expects "testPassed" : false for Encrypt tests!?

### ISSUE THREAD

**Issue by mikolaj-Rianta** [usnistgov/ACVP#591]
**testSessionId**
2131

**vsId**
19030

**Algorithm registration**
```json
    {
      "isSample" : true,
      "algorithms": [{
          "algorithm": "AES-XPN",
          "revision": "1.0.0",
          "direction": ["encrypt", "decrypt"],
          "keyLen": [128],
          "payloadLen": [1576],
          "ivLen": [96],
          "ivGen": "internal",
          "ivGenMode": "8.2.1",
          "aadLen": [200],
          "tagLen": [128],
          "saltGen": "external",
          "saltLen": 96
      }]
    }
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/acvp/v1/testSessions/2131/vectorSets/19030/expected

**Expected behavior**
We are not in a position to mark Excrypt tests as failed we can do it for Decrypt tests

**Additional context**
Submitting test results generates the following response:
```json
[ {
  "acvVersion" : "0.5"
}, {
  "results" : {
    "vsId" : 19030,
    "disposition" : "error",
    "message" : "validation executable failed for: 19030"
  }
} ]
```

If you look at artifacts/draft-fussell-acvp-spec-00.html 10.11.4.1 there is no “error” defined

**Comment by Kritner** [comment]
@mikolaj-Rianta I think I see an issue on our end - we shouldn't be generating potentially "failing" tests for encrypt tests, only for decrypt.  I'm not sure if this is the entirety of the issue you experienced or not, but I'll put in a correction in the next release to demo and we can try again.

**Comment by mikolaj-Rianta** [comment]
Russ,



Thanks a lot! Really appreciate it.



Mikolaj



*From:* Russ Hammett <notifications@github.com>
*Sent:* Tuesday, April 2, 2019 2:23 PM
*To:* usnistgov/ACVP <ACVP@noreply.github.com>
*Cc:* mikolaj-Rianta <mikolajb@rianta.ca>; Mention <
mention@noreply.github.com>
*Subject:* Re: [usnistgov/ACVP] AES-XPN test vector expects "testPassed" :
false for Encrypt tests!? (#591)



@mikolaj-Rianta <https://github.com/mikolaj-Rianta> I think I see an issue
on our end - we shouldn't be generating potentially "failing" tests for
encrypt tests, only for decrypt. I'm not sure if this is the entirety of
the issue you experienced or not, but I'll put in a correction in the next
release to demo and we can try again.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/usnistgov/ACVP/issues/591#issuecomment-479132352>, or mute
the thread

**Comment by Kritner** [comment]
This fix has been deployed to demo.  Let me know if there are any issues.

**Comment by mikolaj-Rianta** [comment]
Thanks a lot! I'd like to give it a try but there seems to be an issue with JWT when I try POST/GET.
I've created a new issue for that.
This is the reply I'm getting from the server: "error" : "vsId was not found in the JWT"

**Comment by mikolaj-Rianta** [comment]
Unfortunately I'm still getting "testPassed" : false in 'Encrypt' tests.
Today (Apr 4, 2019 @ 10:27 AM) I've created a new testSessionId 2733. Requesting expected results for vectorSet 19750 I'm getting "testPassed" : false for encrypt tcId 1, 2, 3, 9, and 11

**Comment by Kritner** [comment]
Hrm... I'll take a look, thanks!

**Comment by Kritner** [comment]
@mikolaj-Rianta I haven't been able to reproduce this locally, I'm going to guess that the build that went out to demo was just prior to the commit that fixed the issue, where I thought it would have included it.

I'll keep this issue open until our next demo push, at which point we can take another look.

Sorry for the confusion!

**Comment by Kritner** [comment]
This has been deployed to demo.  Let us know if there are any issues.

**Comment by mikolaj-Rianta** [comment]
In acvVersion = '1.0', I'm not able to access any of my sessions: e.g. trying to get expected results for testSession 2733 vectorId 19750 returns the following error: "error" : "Cannot properly validate tsId because the claim type isn't supported"

**Comment by Kritner** [comment]
this seems like a separate issue than #607?

**Comment by mikolaj-Rianta** [comment]
Thanks for confirming. I've opened new issue #617

**Comment by Kritner** [comment]
@mikolaj-Rianta just wanted to double check since there have a few updates in here this issue that were due to other issues - can you confirm (with a new session since previously generated JWTs are invalid from prior to the release) that you're no longer seeing failure scenarios on aes-xpn encrypt?

**Comment by mikolaj-Rianta** [comment]
Unfortunately I'm not able to create a new session for AES-XPN here is the error I'm getting: "Incorrectly formatted JSON (18:8): unknown algorithm: AES-XPN with mode: null"
It all used to work before rel 1. Please take a look.

Content-Type: application/json                                                             
[                                             
    {"acvVersion": "1.0"},                    
    {                                         
      "isSample" : true,                      
      "algorithms": [{                        
          "algorithm": "AES-XPN",             
          "revision": "1.0.0",                
          "direction": ["encrypt", "decrypt"],
          "keyLen": [128],                    
          "payloadLen": [1576],               
          "ivLen": [96],                      
          "ivGen": "internal",                
          "ivGenMode": "8.2.1",               
          "aadLen": [200],                    
          "tagLen": [128],                    
          "saltGen": "external",              
          "saltLen": 96                       
      }]                                      
    }                                                                                 
]

**Comment by mikolaj-Rianta** [comment]
Just requested the expected results for the AES-XPN test vector and I don't see "testPassed" : false for 'Encrypt' tests any longer.
Thank you

**Comment by mikolaj-Rianta** [comment]
I've submitted my results, testSession 3012 vectorId 20665. Before submission I compared my results with the expected results and the files were identical (except for white spaces) yet when I query the results I get:
"results" : {                   
  "vsId" : 20665,               
  "disposition" : "incomplete"  
},                              
"retry" : 30

**Comment by Kritner** [comment]
I'll take a look.

**Comment by Kritner** [comment]
A fix has been pushed to demo

**Comment by mikolaj-Rianta** [comment]
Thanks!
Should I create a new session or wait for the new release?

**Comment by Kritner** [comment]
can you submit a new capability registration? I don't recall if the currently implemented features allow for failed vector sets to have their answers submitted again (granted this failure was no fault of yours)

**Comment by mikolaj-Rianta** [comment]
Thanks a lot!
I'll create a new session 3012 cannot be updated: "error" : "Results for Vector Set id: 20665 cannot be updated with status: KAT_RECEIVED"

**Comment by mikolaj-Rianta** [comment]
Created new session 3027 vectorId 20737, submitted my results and got a pass!
Thanks for such a quick turnaround!

**Comment by Kritner** [comment]
no problem, glad it's working!
