### ISSUE TITLE
RSA test vector generation not producing vectors, or producing invalid vectors

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#740]
@Kritner @celic 
I'm seeing something similar to #732 after submitting the simplest RSA keyGen registration.

[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"RSA","revision":"1.0","mode":"keyGen","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"infoGeneratedByServer":true,"pubExpMode":"fixed","fixedPubExp":"010001","keyFormat":"standard","capabilities":[{"randPQ":"B.3.4","properties":[{"modulo":2048,"hashAlg":["SHA2-256"]}]}]}]}]

  "vsId" : 72162,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 72162"

Did I miss a change in the registration requirements ?

_Originally posted by @bfussell in https://github.com/usnistgov/ACVP/issues/719#issuecomment-550357609_

**Comment by Kritner** [comment]
@bfussell a fix was pushed out related to this, can you give it another go?

**Comment by bfussell** [comment]
Works fine now, thanks !

**Comment by bfussell** [comment]
Still seeing this from time to time.
testSession: 42338
Failing vectorSet: 85886

This time it appears to be ECDSA.

**Comment by celic** [comment]
85886 on our end is available for download. Do you have an estimate of how long it took to run?

**Comment by bfussell** [comment]
After 32 retries @ 30 seconds each I got an empty response to my GET.
Normally the GET would return:

[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 85886,
  "retry" : 30
} ]

**Comment by celic** [comment]
Yeah, the expectation is that you would receive that familiar retry-30 message until the vector set is ready. Any other behavior is not intended. The first few retries would have content correct? It is just the last one (few?) that were empty for a particular vector set ID?

**Comment by bfussell** [comment]
That's correct, 32 times we got the retry message and then we got an empty message which caused our client to flag an error and exit.

**Comment by celic** [comment]
We will do some digging to see if we can identify the cause on our end. Do you have an approximate time? 1:00pm EST?

**Comment by bfussell** [comment]
It was after lunch, no earlier than 1:00 EST but I don't have an exact time. Sorry.

**Comment by celic** [comment]
We looked at the logs and found the inbound request, the GET for the prompt and that the server replied with a 200 HTTP status. We do not store the actual content replied in our logs. Nothing seems out of the ordinary here. Nothing on our end even reports an error here. The vector set did complete processing (eventually) and became available at the GET URL. I'm sorry to say we don't have an answer for you. If it happens again please let us know so we can try to figure out a pattern if it exists.

**Comment by AlexThurston** [comment]
@celic I have a test session (45155) where I have a slew of various capabilities.  In that set es I have three modes for RSA: KeyGen, SigGen, SigVer.

SigGen vectors seem to have been generated correctly, but the other two are in the same boat as described here and in a few other issues.

The vectors sets that haven't been generated are: 95589 and 95587.

Both them respond with:
```
{
  "status": "error during vector generation",
  "message": "failed to generate tests for: 95589"
}
```

I wasn't sure if I should open up another issue or tack onto this one.  It does seem to be very similar to the experiences detailed here.

**Comment by Kritner** [comment]
@AlexThurston sorry for the delay...

95587:

```
{
	"vsId": 95587,
	"isSample": true,
	"algorithm": "RSA",
	"mode": "keyGen",
	"revision": "1.0",
	"fixedPubExp": "10001",
	"infoGeneratedByServer": true,
	"pubExpMode": "fixed",
	"keyFormat": "standard",
	"capabilities": [{
		"randPQ": "B.3.3",
		"properties": [{
			"modulo": 2048,
			"primeTest": ["tblC2", "tblC3"]
		}, {
			"modulo": 3072,
			"primeTest": ["tblC2", "tblC3"]
		}]
	}, {
		"randPQ": "B.3.6",
		"properties": [{
			"modulo": 2048,
			"primeTest": ["tblC2", "tblC3"]
		}, {
			"modulo": 3072,
			"primeTest": ["tblC2", "tblC3"]
		}]
	}]
}
```

The fixed public exponent (and all bitstrings for that matter) are expected as full bytes. 

95589

```
{
	"vsId": 95589,
	"isSample": true,
	"algorithm": "RSA",
	"mode": "sigVer",
	"revision": "1.0",
	"pubExpMode": "fixed",
	"capabilities": [{
		"sigType": "pkcs1v1.5",
		"properties": [{
			"modulo": 1024,
			"hashPair": [{
				"hashAlg": "SHA-1"
			}, {
				"hashAlg": "SHA2-224"
			}, {
				"hashAlg": "SHA2-256"
			}, {
				"hashAlg": "SHA2-384"
			}, {
				"hashAlg": "SHA2-512"
			}, {
				"hashAlg": "SHA2-512/224"
			}, {
				"hashAlg": "SHA2-512/256"
			}]
		}, {
			"modulo": 2048,
			"hashPair": [{
				"hashAlg": "SHA-1"
			}, {
				"hashAlg": "SHA2-224"
			}, {
				"hashAlg": "SHA2-256"
			}, {
				"hashAlg": "SHA2-384"
			}, {
				"hashAlg": "SHA2-512"
			}, {
				"hashAlg": "SHA2-512/224"
			}, {
				"hashAlg": "SHA2-512/256"
			}]
		}, {
			"modulo": 3072,
			"hashPair": [{
				"hashAlg": "SHA-1"
			}, {
				"hashAlg": "SHA2-224"
			}, {
				"hashAlg": "SHA2-256"
			}, {
				"hashAlg": "SHA2-384"
			}, {
				"hashAlg": "SHA2-512"
			}, {
				"hashAlg": "SHA2-512/224"
			}, {
				"hashAlg": "SHA2-512/256"
			}]
		}]
	}, {
		"sigType": "pss",
		"properties": [{
			"modulo": 1024,
			"hashPair": [{
				"hashAlg": "SHA-1",
				"saltLen": 20
			}, {
				"hashAlg": "SHA2-224",
				"saltLen": 28
			}, {
				"hashAlg": "SHA2-256",
				"saltLen": 32
			}, {
				"hashAlg": "SHA2-384",
				"saltLen": 48
			}, {
				"hashAlg": "SHA2-512",
				"saltLen": 64
			}, {
				"hashAlg": "SHA2-512/224",
				"saltLen": 28
			}, {
				"hashAlg": "SHA2-512/256",
				"saltLen": 32
			}]
		}, {
			"modulo": 2048,
			"hashPair": [{
				"hashAlg": "SHA-1",
				"saltLen": 20
			}, {
				"hashAlg": "SHA2-224",
				"saltLen": 28
			}, {
				"hashAlg": "SHA2-256",
				"saltLen": 32
			}, {
				"hashAlg": "SHA2-384",
				"saltLen": 48
			}, {
				"hashAlg": "SHA2-512",
				"saltLen": 64
			}, {
				"hashAlg": "SHA2-512/224",
				"saltLen": 28
			}, {
				"hashAlg": "SHA2-512/256",
				"saltLen": 32
			}]
		}, {
			"modulo": 3072,
			"hashPair": [{
				"hashAlg": "SHA-1",
				"saltLen": 20
			}, {
				"hashAlg": "SHA2-224",
				"saltLen": 28
			}, {
				"hashAlg": "SHA2-256",
				"saltLen": 32
			}, {
				"hashAlg": "SHA2-384",
				"saltLen": 48
			}, {
				"hashAlg": "SHA2-512",
				"saltLen": 64
			}, {
				"hashAlg": "SHA2-512/224",
				"saltLen": 28
			}, {
				"hashAlg": "SHA2-512/256",
				"saltLen": 32
			}]
		}]
	}],
	"conformances": ["SP800-106"]
}
```

The salt length of 64 is invalid, 62 is the max for a modulo of 1024 - I'm not sure the reasoning behind this, though it has come up before.  Perhaps @celic recalls.  Additionally the registration specified a fixed public exponent, but did not specify the exponent. 

#684 / #685 related.

**Comment by Kritner** [comment]
The initial issue related to this is resolved, any further issues with RSA would be due to something separate.

**Comment by AlexThurston** [comment]
@Kritner Awesome, with this info, I was able to get my vector sets.  Thanks for that.

Out of curiosity, was there feedback from the server that I missed that would have told me why my registration was in fact incorrect?

**Comment by Kritner** [comment]
> Out of curiosity, was there feedback from the server that I missed that would have told me why my registration was in fact incorrect?

@AlexThurston no unfortunately, we're doing some internal changes that are necessary to eventually roll out #684 and #685 which will alleviate a lot of this, it's just going to take some more time.
