### ISSUE TITLE
Unable to receive verdicts for some vsID

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/ACVP#882]
I have been trying to post certain vsID for hours now and it seems like the server will not send the verdict.

The vsID example are:
testID 88372 / vsID 226800
testID 88385 / vsID 226868
testID 88389 / vsID 226889

The proxy waits for hours for the verdicts which seem to never be sent by the server.

**Comment by celic** [comment]
We never received the responses for 226800, 226868 or 226889. I notice these are all GCM, and seem to be quite large registrations. Let me see if I can find any errors during upload. Were there any errors reported by the client during upload?

**Comment by celic** [comment]
In response to this we are adding a check on the server. If you GET the results while the server has not yet received the responses, the server will inform you of that rather than enter an "infinite" retry-30. 

The server would never stop replying with a retry-30 in this case as the client thinks the upload was successful, but the server has nothing to process. That is a more interesting error though.

**Comment by celic** [comment]
Our internal logs say that the response that was being uploaded was too large. A 413 HTTP Status code was returned to the client after submitting the responses for 226800. How large was that file?

**Comment by QuentinGouchet** [comment]
The response file for testID 88389/ vsID 226889 is 61.4MB, which is indeed large.

**Comment by QuentinGouchet** [comment]
I do indeed receive error 413

**Comment by celic** [comment]
A fix has been deployed to Demo.

**Comment by QuentinGouchet** [comment]
Chris,
I am still getting some HTTP error status code: 413 for testID 88389 / vsID 226889.
